# Generated by Django 4.2 on 2025-12-01 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_app', '0002_frequentquestion_offenselog_feedback'),
    ]

    operations = [
        # 1. Add new fields to Feedback model
        migrations.AddField(
            model_name='feedback',
            name='chatbot_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot_app.chatbotresponse'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(blank=True, choices=[('positive', 'Yaxshi 👍'), ('negative', 'Yomon 👎'), ('corrected', "To'g'rilandi ✏️")], max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin izohlar'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin tomonidan tasdiqlangan'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        
        # 2. Create ManualCorrection model
        migrations.CreateModel(
            name='ManualCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_pattern', models.TextField(help_text='Savol namunasi (regex yoki oddiy matn)')),
                ('correct_answer', models.TextField(help_text="To'g'ri javob")),
                ('priority', models.IntegerField(default=1, help_text='Yuqori raqam = yuqori ustuvorlik')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Necha marta ishlatilgan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
