# Generated by Django 4.2 on 2025-12-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0003_auto_20251201_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='corrected_answer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(blank=True, choices=[('positive', 'Yaxshi 👍'), ('negative', 'Yomon 👎')], max_length=20),
        ),
    ]
