# Generated by Django 4.2 on 2025-12-02 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_app', '0004_remove_feedback_corrected_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='corrected_answer',
            field=models.TextField(blank=True, help_text="To'g'rilangan javob (admin tomonidan)"),
        ),
        migrations.AddField(
            model_name='feedback',
            name='corrected_at',
            field=models.DateTimeField(blank=True, help_text="To'g'rilangan vaqt", null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='corrected_by',
            field=models.ForeignKey(blank=True, help_text="Kim to'g'rilagan", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='correction_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('corrected', "To'g'rilandi"), ('ignored', "E'tiborga olinmadi")], default='pending', help_text="To'g'rilash holati", max_length=20),
        ),
    ]
