# Generated by Django 4.2 on 2025-12-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0005_feedback_corrected_answer_feedback_corrected_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question',
        ),
    ]
