# Generated by Django 4.2 on 2025-12-04 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_app', '0006_remove_legacy_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='PDF, Word yoki Text fayl yuklang', null=True, upload_to='documents/%Y/%m/')),
                ('url', models.URLField(blank=True, help_text='Veb-sahifa URL manzili', null=True)),
                ('title', models.CharField(help_text='Hujjat nomi', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Qisqacha tavsif')),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('url', 'Web URL'), ('text', 'Text File')], help_text='Hujjat turi', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Qayta ishlanmoqda'), ('completed', 'Tayyor'), ('failed', 'Xatolik')], default='pending', help_text='Qayta ishlash holati', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Qayta ishlangan vaqt', null=True)),
                ('chunks_created', models.PositiveIntegerField(default=0, help_text="Yaratilgan chunk'lar soni")),
                ('error_message', models.TextField(blank=True, help_text="Xatolik xabari (agar bo'lsa)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
