# Generated by Django 4.2 on 2025-12-15 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0008_chatsession_chatbotresponse_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_queries', models.IntegerField(default=0)),
                ('unique_sessions', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('avg_validation_score', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('hallucination_count', models.IntegerField(default=0)),
                ('top_intents', models.JSONField(default=dict)),
                ('avg_user_rating', models.FloatField(blank=True, null=True)),
                ('feedback_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Stats',
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_intent',
            field=models.CharField(blank=True, help_text="Oxirgi savol intent'i", max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_turns',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField(help_text='Suhbatdagi tartib raqami')),
                ('user_message', models.TextField(help_text='Foydalanuvchi savoli')),
                ('bot_response', models.TextField(help_text='Bot javobi')),
                ('intent', models.CharField(blank=True, help_text="Savol intent'i", max_length=50)),
                ('context_used', models.JSONField(default=list, help_text='Qaysi context ishlatilgan')),
                ('sources_used', models.JSONField(default=list, help_text='Qaysi manbalardan foydalanilgan')),
                ('confidence_score', models.FloatField(default=0.0, help_text='RAG confidence')),
                ('validation_score', models.FloatField(default=0.0, help_text='Hallucination check score')),
                ('response_time', models.FloatField(default=0.0, help_text='Javob vaqti (soniyada)')),
                ('was_cached', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='chatbot_app.chatsession')),
            ],
            options={
                'ordering': ['turn_number'],
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('query', models.TextField()),
                ('query_length', models.IntegerField(default=0)),
                ('intent', models.CharField(blank=True, db_index=True, max_length=50)),
                ('detected_language', models.CharField(default='uz', max_length=10)),
                ('response', models.TextField(blank=True)),
                ('response_length', models.IntegerField(default=0)),
                ('response_time', models.FloatField(default=0.0)),
                ('was_cached', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('validation_score', models.FloatField(default=0.0)),
                ('hallucination_risk', models.FloatField(default=0.0)),
                ('grounding_score', models.FloatField(default=0.0)),
                ('sources_count', models.IntegerField(default=0)),
                ('top_source_confidence', models.FloatField(default=0.0)),
                ('sources_used', models.JSONField(default=list)),
                ('search_type', models.CharField(choices=[('semantic', 'Semantic Search'), ('keyword', 'Keyword Search'), ('hybrid', 'Hybrid Search')], default='hybrid', max_length=20)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_feedback_text', models.TextField(blank=True)),
                ('error_occurred', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='chatbot_app.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Analytics',
                'verbose_name_plural': 'Chat Analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['session', 'turn_number'], name='chatbot_app_session_ec2a86_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['timestamp'], name='chatbot_app_timesta_c42902_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['intent'], name='chatbot_app_intent_9024d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationturn',
            unique_together={('session', 'turn_number')},
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['timestamp', 'intent'], name='chatbot_app_timesta_720e92_idx'),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['confidence_score'], name='chatbot_app_confide_007e10_idx'),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['error_occurred'], name='chatbot_app_error_o_069e9c_idx'),
        ),
    ]
