# Generated by Django 4.2 on 2025-12-15 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_app', '0009_dailystats_chatsession_last_intent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_uz', models.CharField(blank=True, help_text="O'zbek tilidagi nomi", max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji yoki icon nomi', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='chatbot_app.category')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Asosiy savol')),
                ('question_variants', models.JSONField(blank=True, default=list, help_text="Savolning boshqa variantlari (list). Masalan: ['When is admission?', 'Admission dates?']")),
                ('answer', models.TextField(help_text='Javob matni')),
                ('short_answer', models.CharField(blank=True, help_text='Qisqa javob (optional)', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Qidiruv uchun teglar. Masalan: ['admission', 'dates', 'june']")),
                ('keywords', models.TextField(blank=True, help_text="Qidiruv uchun kalit so'zlar (vergul bilan ajratilgan)")),
                ('source_url', models.URLField(blank=True, help_text="Ma'lumot manbasi URL")),
                ('source_name', models.CharField(blank=True, help_text='Manba nomi', max_length=100)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Past'), (2, "O'rta"), (3, 'Yuqori'), (4, 'Juda muhim')], default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin tomonidan tekshirilgan')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('not_helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('embedding_updated', models.BooleanField(default=False, help_text="ChromaDB ga qo'shilganmi")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='chatbot_app.category')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='chatbot_app.topic')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQlar',
                'ordering': ['-priority', '-view_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Kalit nomi. Masalan: admission_start_date', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Qiymat')),
                ('info_type', models.CharField(choices=[('date', 'Sana'), ('price', 'Narx'), ('number', 'Raqam'), ('text', 'Matn'), ('contact', 'Aloqa')], default='text', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Tavsif', max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Dinamik ma'lumot",
                'verbose_name_plural': "Dinamik ma'lumotlar",
                'ordering': ['key'],
            },
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_active'], name='chatbot_app_categor_8ae48f_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['priority', '-view_count'], name='chatbot_app_priorit_c4b641_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['embedding_updated'], name='chatbot_app_embeddi_8247f4_idx'),
        ),
    ]
