# Generated by Django 4.2 on 2025-12-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0010_category_topic_faq_dynamicinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', help_text='Suhbat tili', max_length=2),
        ),
    ]
