# Generated by Django 4.2 on 2025-12-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0011_chatsession_language'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatbotresponse',
            index=models.Index(fields=['session', '-created_at'], name='chatbot_app_session_b7e71a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotresponse',
            index=models.Index(fields=['user', '-created_at'], name='chatbot_app_user_id_c24dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotresponse',
            index=models.Index(fields=['-created_at'], name='chatbot_app_created_66e46d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='chatbot_app_user_id_50a9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['created_at', 'is_active'], name='chatbot_app_created_986ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['language'], name='chatbot_app_languag_544368_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id', 'is_active'], name='chatbot_app_session_0a02bc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['-updated_at'], name='chatbot_app_updated_52f8eb_idx'),
        ),
    ]
