# Generated by Django 4.2 on 2026-01-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0012_chatbotresponse_chatbot_app_session_b7e71a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text="Confidence, sources, response_time va boshqa meta-ma'lumotlar")),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='chatbot_app.chatsession')),
            ],
            options={
                'ordering': ['turn_number'],
            },
        ),
        migrations.CreateModel(
            name='SessionMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, help_text='Suhbatning qisqa mazmuni (AI tomonidan yangilanadi)')),
                ('last_intent', models.CharField(blank=True, max_length=50)),
                ('interaction_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='chatbot_app.chatsession')),
            ],
            options={
                'verbose_name': 'Session Memory',
            },
        ),
        migrations.DeleteModel(
            name='ConversationTurn',
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['session', 'turn_number'], name='chatbot_app_session_6f5380_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['timestamp'], name='chatbot_app_timesta_4cb65a_idx'),
        ),
    ]
