# Generated by Django 4.2 on 2026-01-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0013_chatlog_sessionmemory_delete_conversationturn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, help_text='Chunk sarlavhasi', max_length=255)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('chroma_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chatbot_app.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.RemoveField(
            model_name='chatbotresponse',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatbotresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='chatbot_response',
        ),
        migrations.AddField(
            model_name='feedback',
            name='chat_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot_app.chatlog'),
        ),
        migrations.DeleteModel(
            name='ChatbotResponse',
        ),
    ]
