# Generated by Django 4.2 on 2026-01-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0014_documentchunk_remove_chatbotresponse_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], max_length=2)),
                ('question', models.TextField(help_text='Savol tarjimasi')),
                ('answer', models.TextField(help_text='Javob tarjimasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chatbot_app.faq')),
            ],
            options={
                'verbose_name': 'FAQ Tarjimasi',
                'verbose_name_plural': 'FAQ Tarjimalari',
                'unique_together': {('faq', 'language')},
            },
        ),
    ]
