# Generated by Django 4.2 on 2026-01-15 05:23

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_app', '0015_faqtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', max_length=10)),
                ('lang', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('text', models.TextField(default='')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of source IDs used (doc_id, chunk_id, faq_id)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('lang', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2)),
                ('found_type', models.CharField(choices=[('faq', 'FAQ'), ('doc', 'Document'), ('none', 'Not Found')], default='none', max_length=10)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Search latency in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='chatanalytics',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatlog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyStats',
        ),
        migrations.DeleteModel(
            name='FrequentQuestion',
        ),
        migrations.RemoveField(
            model_name='manualcorrection',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='OffenseLog',
        ),
        migrations.RemoveField(
            model_name='sessionmemory',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='dynamicinfo',
            options={'verbose_name': "Dinamik ma'lumot", 'verbose_name_plural': "Dinamik ma'lumotlar"},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['category', 'order', '-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQlar'},
        ),
        migrations.RemoveIndex(
            model_name='faq',
            name='chatbot_app_categor_8ae48f_idx',
        ),
        migrations.RemoveIndex(
            model_name='faq',
            name='chatbot_app_priorit_c4b641_idx',
        ),
        migrations.RemoveIndex(
            model_name='faq',
            name='chatbot_app_embeddi_8247f4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='faqtranslation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='document',
            name='chunks_created',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='char_count',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='chroma_id',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dynamicinfo',
            name='info_type',
        ),
        migrations.RemoveField(
            model_name='dynamicinfo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dynamicinfo',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='dynamicinfo',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='embedding_updated',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='not_helpful_count',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_variants',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='short_answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='chat_log',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='corrected_answer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='corrected_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='corrected_by',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='correction_status',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('html', 'Web/HTML'), ('text', 'Text')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='chunk_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID in Vector DB (Qdrant/Chroma)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='lang',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan'), ('archived', 'Arxivlangan')], default='published', max_length=20),
        ),
        migrations.RenameField(
            model_name='faqtranslation',
            old_name='language',
            new_name='lang',
        ),
        migrations.AddField(
            model_name='faqtranslation',
            name='search_tsv',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Yuklangan'), ('processing', 'Qayta ishlanmoqda'), ('ready', 'Tayyor'), ('failed', 'Xatolik')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dynamicinfo',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dynamicinfo',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dynamicinfo',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faqtranslation',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faqtranslation',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='faqtranslation',
            unique_together={('faq', 'lang')},
        ),
        migrations.AddIndex(
            model_name='faqtranslation',
            index=models.Index(fields=['lang'], name='chatbot_app_lang_92bcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='faqtranslation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_tsv'], name='chatbot_app_search__31e137_gin'),
        ),
        migrations.DeleteModel(
            name='ChatAnalytics',
        ),
        migrations.DeleteModel(
            name='ChatLog',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='ManualCorrection',
        ),
        migrations.DeleteModel(
            name='SessionMemory',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_app.conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='faqtranslation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faqtranslation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot_app.message'),
        ),
    ]
