# Generated by Django 4.2 on 2026-01-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0016_conversation_message_searchlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sources',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='platform',
            field=models.CharField(default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_id',
            field=models.CharField(db_index=True, default='legacy_user', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Sources, feedback, etc.'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='faqtranslation',
            name='lang',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=2),
        ),
    ]
