# Generated by Django 4.2 on 2026-01-15 06:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0017_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='faqtranslation',
            name='chatbot_app_search__31e137_gin',
        ),
        migrations.RenameField(
            model_name='faqtranslation',
            old_name='search_tsv',
            new_name='answer_tsv',
        ),
        migrations.AddField(
            model_name='faq',
            name='canonical_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='faqtranslation',
            name='embedding_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faqtranslation',
            name='question_tsv',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqtranslation',
            name='question_variants',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='faqtranslation',
            name='short_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='faqtranslation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['question_tsv'], name='chatbot_app_questio_525bd7_gin'),
        ),
        migrations.AddIndex(
            model_name='faqtranslation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['answer_tsv'], name='chatbot_app_answer__41aea4_gin'),
        ),
    ]
