# Generated by Django 4.2 on 2026-01-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0018_remove_faqtranslation_chatbot_app_search__31e137_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='intent_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords to trigger this category intent'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='faq',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Is this information up to date?'),
        ),
        migrations.AddField(
            model_name='faq',
            name='year',
            field=models.PositiveIntegerField(default=2024, help_text='The year this information applies to'),
        ),
    ]
