# Generated by Django 4.2 on 2026-01-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0019_category_intent_keywords_document_is_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqtranslation',
            name='short_answer',
        ),
    ]
