# Generated by Django 4.2 on 2026-01-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0020_remove_faqtranslation_short_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchLog',
        ),
    ]
