# Generated by Django 4.2 on 2026-01-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0021_delete_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicinfo',
            name='intent_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords to trigger this dynamic info'),
        ),
    ]
