# Generated by Django 4.2 on 2026-01-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0022_dynamicinfo_intent_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lang',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], db_index=True, default='uz', max_length=2),
        ),
    ]
