# Generated by Django 4.2 on 2026-01-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0023_document_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='parent_context',
            field=models.TextField(blank=True, help_text='Parent document/section context'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='row_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured row data if from table'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='section_title',
            field=models.CharField(blank=True, help_text='Section or heading this chunk belongs to', max_length=500),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='table_headers',
            field=models.JSONField(blank=True, default=list, help_text='Column headers if from table'),
        ),
        migrations.AddField(
            model_name='dynamicinfo',
            name='value_en',
            field=models.TextField(blank=True, help_text='Value in English'),
        ),
        migrations.AddField(
            model_name='dynamicinfo',
            name='value_ru',
            field=models.TextField(blank=True, help_text='Value in Russian'),
        ),
        migrations.AddField(
            model_name='dynamicinfo',
            name='value_uz',
            field=models.TextField(blank=True, help_text='Value in Uzbek'),
        ),
        migrations.AddField(
            model_name='faqtranslation',
            name='dynamic_variables',
            field=models.JSONField(blank=True, default=list, help_text="DynamicInfo keys used in answer (e.g., ['tuition_fee_journalism'])"),
        ),
        migrations.AlterField(
            model_name='dynamicinfo',
            name='value',
            field=models.TextField(help_text='Deprecated: use value_uz instead'),
        ),
    ]
