# Generated by Django 4.2 on 2026-01-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0024_documentchunk_parent_context_documentchunk_row_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('is_cache_hit', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=10)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='chatbot_app.message')),
            ],
            options={
                'verbose_name': 'Chat Analitikasi',
                'verbose_name_plural': 'Chat Analitikalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
