# Generated by Django 4.2 on 2026-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0025_chatanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatanalytics',
            name='error_log',
            field=models.TextField(blank=True, help_text='Raw error logs if failure occurred', null=True),
        ),
    ]
